Updated the UI for edit/save functionality for user details/info when displaying
Innovateninjas/Paws-frontend pull request #286
Opened 2024-05-11 12:22 UTC by dev-rsiva

## Description
I updated the complete UI with in-line editing and saving the existing/logged in user information, such as name and phone number.
  1. Validation for name is implemented by displaying an error message when the user inputs invalid information.
 2. Validation for phone numbers is implemented by displaying an error message when the user inputs invalid information.
 
## Related Issue

Note: Sign-up/login is not working, so, i have changed the conditions/state and worked in the project. Once the changes are made, I restore the original conditions/state.

## Screenshots / GIFs (if applicable)

 The video of the implemented UI is attached for your reference.

[

https://github.com/Innovateninjas/Paws-frontend/assets/131841846/cbaf5d16-55a9-430a-82b3-224e46d0ba7c

](url)

## Checklist:

 -

## Additional Notes
 
-

2024-05-12 05:57 UTC, codewarnab commented
you can contact @anirbanmajumder0  for any query about sending request to backend updating details

2024-05-12 06:04 UTC, codewarnab commented
> ## Description
> I updated the complete UI with in-line editing and saving the existing/logged in user information, such as name and phone number.
> 
> 1. Validation for name is implemented by displaying an error message when the user inputs invalid information.
> 2. Validation for phone numbers is implemented by displaying an error message when the user inputs invalid information.
> 
> ## Related Issue
> Note: Sign-up/login is not working, so, i have changed the conditions/state and worked in the project. Once the changes are made, I restore the original conditions/state.
> 
> ## Screenshots / GIFs (if applicable)
> The video of the implemented UI is attached for your reference.
> 
> [
> 
>  11.05.2024_17.29.42_REC.mp4 
> ](url)
> 
> ## Checklist:
> 
> ## Additional Notes

just checked registration and login is working file please check the `contribution.md` for setting the envs and if you are still unable to login please share what issue are your facing

2024-05-12 12:47 UTC, anirbanmajumder0 requested changes

2024-05-12 12:47 UTC, anirbanmajumder0 commented on src/pages/user/UserProfile.jsx
> +      console.log(updatedUserData);
Here u should send the updated data to the backend .

2024-05-12 15:37 UTC, dev-rsiva commented on src/pages/user/UserProfile.jsx
> +      console.log(updatedUserData);
Can i know the end points where should i send it. I dont have enough knowledge in backend system using python.

2024-05-25 13:32 UTC, anirbanmajumder0 commented on src/pages/user/UserProfile.jsx
> +      console.log(updatedUserData);
const url = process.env.REACT_APP_BACKEND_URL;
      const response = await fetch(`${url}/profile/`, {
        method: "POST",
        headers: {
          "Authorization": `Token ${csrftoken}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          profile_image: imageUrl,
        }), like this but use  name/ phone_number  in the body

2024-05-25 13:53 UTC, codewarnab commented
@dev-rsiva  it will be better if you create a new branch/fork and  put the changes their UserProfile.jsx has changed much

2024-05-29 05:16 UTC, closed without merging