LoginPage validation update
Innovateninjas/Paws-frontend pull request #312
Opened 2024-05-13 14:55 UTC by HardCoder404

# Description : 
### In this bug, I just added a validation in Login Page.

# ScreenShot : 
![Screenshot 2024-05-13 201921](https://github.com/Innovateninjas/Paws-frontend/assets/127084297/e089b43a-d735-4b34-b7a1-6f1eeaee9a0d)
![Screenshot 2024-05-13 201937](https://github.com/Innovateninjas/Paws-frontend/assets/127084297/d077a832-d88f-467f-b4f9-0a276e45a58d)

2024-05-16 07:45 UTC, rishicds commented
Hi @HardCoder404 , please fix the merge conflicts, it will be merged after that, also mention which issue this closes.

2024-05-16 12:29 UTC, HardCoder404 commented
The conflict has been resolved. Please review and merged it.

2024-05-16 14:40 UTC, codewarnab requested changes
sorry to bother you again please move the validation inside the login function which is in the userAuthService.js it will maintain the code quality .
also their is already email validatory so no need to valid it two times

2024-05-16 14:41 UTC, codewarnab commented on src/pages/user/UserRegistration.jsx
> +=======
remove this thing also

2024-05-23 12:19 UTC, codewarnab commented
@HardCoder404 its been 10 days give update or we  have to close the pr

2024-05-29 05:17 UTC, closed without merging