Password must be strong with specific rules issue#337
Innovateninjas/Paws-frontend pull request #345
Opened 2024-05-16 16:01 UTC by kapilG0

## Description
Now Register button is disabled if password is not good
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None"]

## Screenshots / GIFs (if applicable)
[Attach any relevant screenshots or GIFs demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [ ] I have added/updated relevant documentation (if needed)
- [x] I have tested the changes locally and they function as expected
- [ ] I have ensured my code follows the project's coding standards

## Additional Notes
[Add any additional notes or context about the changes made]

2024-05-16 16:38 UTC, codewarnab commented
please mention related issue

2024-05-16 16:40 UTC, kapilG0 commented
> please mention related issue

Done

2024-05-16 18:55 UTC, rishicds commented
Hi @kapilG0 , please update your branch

2024-05-17 03:41 UTC, kapilG0 commented
> Hi @kapilG0 , please update your branch

Do you mean I should sync my forked repo then raise pr ?

2024-05-17 14:48 UTC, codewarnab requested changes
@kapilG0 sync your branch resolve conflicts then commit again

2024-05-17 14:48 UTC, codewarnab commented on src/pages/user/UserRegistration.jsx
> +                        setErrorMessage,
why did you passed this in this registartion function ?

2024-05-17 15:03 UTC, closed without merging

2024-05-17 16:35 UTC, kapilG0 commented
> @kapilG0 sync your branch resolve conflicts then commit again

Hello @codewarnab I raised new pull request https://github.com/Innovateninjas/Paws-frontend/pull/351. Please check after sync my forked repo. Thanks