Riddhipatch2
Innovateninjas/Paws-frontend pull request #362
Opened 2024-05-19 07:02 UTC by Riddhi162

## Description
[Please include a brief description of the changes or features added]
I have made the page responsive also improved the font positioning and size etc.

## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None"]

## Screenshots / GIFs (if applicable)
[Attach any relevant screenshots or GIFs demonstrating the changes]
![Screenshot 2024-05-19 122923](https://github.com/Innovateninjas/Paws-frontend/assets/135015856/f0e4a64c-234b-49f8-bc79-4aa727b069a1)
![Screenshot 2024-05-19 122929](https://github.com/Innovateninjas/Paws-frontend/assets/135015856/88d93a7f-e502-48e3-97f9-ea5514b08de1)
![Screenshot 2024-05-19 122759](https://github.com/Innovateninjas/Paws-frontend/assets/135015856/8184f2ac-41de-4874-be59-3fdfbef61a95)

## Checklist:
- [ ] I have performed a self-review of my code
- [ ] I have added/updated relevant documentation (if needed)
- [ ] I have tested the changes locally and they function as expected
- [ ] I have ensured my code follows the project's coding standards

## Additional Notes
[Add any additional notes or context about the changes made]

2024-05-25 14:06 UTC, codewarnab requested changes

2024-05-25 14:06 UTC, codewarnab commented on src/pages/user/ReportIncidentPages/AnimalDetailsPage/AnimalDetailsPage.jsx
> +    <div className="">
whats this empty classname for ?

2024-05-25 14:06 UTC, codewarnab commented on src/pages/user/ReportIncidentPages/AnimalDetailsPage/AnimalDetailsPage.jsx
> +
change it to describe severity

2024-05-25 14:08 UTC, codewarnab commented
@Riddhi162  you have to create two separate pr from two separate brances  for the two pages contact information and animal details page 
also dont forget to mention the issue in decsription

2024-05-25 16:12 UTC, Riddhi162 commented
ohhh ok ill make the necessary changes.

2024-05-30 07:05 UTC, codewarnab commented
this one is the old version of #416 right ? if yes please close the pr

2024-05-30 12:59 UTC, Riddhi162 commented
ok will do so

2024-05-30 12:59 UTC, closed without merging