responsive sign up completed
Innovateninjas/Paws-frontend pull request #407
Opened 2024-05-26 05:25 UTC by Varsani2520

## Description
[Please include a brief description of the changes or features added]
in full screen and mobile screen display different different UI

## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None"]
responsive UI of sign up #374  and closed #374 

## Screenshots / GIFs (if applicable)
[Attach any relevant screenshots or GIFs demonstrating the changes]
in full screen:
![image](https://github.com/Innovateninjas/Paws-frontend/assets/137641079/ad4921c6-3bdb-4154-ae6f-1b36b7e392b7)
in mobile screen:
![image](https://github.com/Innovateninjas/Paws-frontend/assets/137641079/209b5626-8d49-4fe5-bddc-f99720bc0ad8)

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have added/updated relevant documentation (if needed)
- [x] I have tested the changes locally and they function as expected
- [x] I have ensured my code follows the project's coding standards

## Additional Notes
[Add any additional notes or context about the changes made]

2024-05-26 05:28 UTC, Varsani2520 commented
Hey @rishicds ,
review and merged it

2024-05-26 07:01 UTC, codewarnab commented
> ## Description
> [Please include a brief description of the changes or features added] in full screen and mobile screen display different different UI
> 
> ## Related Issue
> [Cite any related issue(s) this pull request addresses. If none, simply state "None"] responsive UI of sign up #374 and closed #374
> 
> ## Screenshots / GIFs (if applicable)
> [Attach any relevant screenshots or GIFs demonstrating the changes] in full screen: ![image](https://private-user-images.githubusercontent.com/137641079/333849300-ad4921c6-3bdb-4154-ae6f-1b36b7e392b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDcwNTAsIm5iZiI6MTcxNjcwNjc1MCwicGF0aCI6Ii8xMzc2NDEwNzkvMzMzODQ5MzAwLWFkNDkyMWM2LTNiZGItNDE1NC1hZTZmLTFiMzZiN2UzOTJiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQwNjU5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYzg2YjZjMThlZmU4ZTg3MjcxNjRlYjljNDUxNDY0YWFmMGFhMjc1OGI2Mjg5OWYzMmYzZjU4YjI3YjkzZjhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5bxqYYSUuwqqGQySB69VkaT3dz9zgnExEiHmYKY2Hu4) in mobile screen: ![image](https://private-user-images.githubusercontent.com/137641079/333849386-209b5626-8d49-4fe5-bddc-f99720bc0ad8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDcwNTAsIm5iZiI6MTcxNjcwNjc1MCwicGF0aCI6Ii8xMzc2NDEwNzkvMzMzODQ5Mzg2LTIwOWI1NjI2LThkNDktNGZlNS1iZGRjLWY5OTcyMGJjMGFkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQwNjU5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYTAxMjI3ZGI3ZTlhZWRhYzVjNDNhOGM3MWQwOTU2YjFkZGQ4NjZiYzc4YzExMGM1YjRmNTM4YWI4ZTQ0Zjk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M22hhJtjvPZTbEOCLZXpgJwBe2g2XcmLHebEjcVgJvE)
> 
> ## Checklist:
> * [x]  I have performed a self-review of my code
> * [x]  I have added/updated relevant documentation (if needed)
> * [x]  I have tested the changes locally and they function as expected
> * [x]  I have ensured my code follows the project's coding standards
> 
> ## Additional Notes
> [Add any additional notes or context about the changes made]

![image](https://github.com/Innovateninjas/Paws-frontend/assets/94959855/47034796-89a1-4140-8b4b-1cea0c95695e)
just tested it locally it is not responsive your phone can you share the full screen with dimesions also for mobile

2024-05-26 07:02 UTC, codewarnab requested changes

2024-05-26 07:02 UTC, codewarnab commented on src/pages/user/UserRegistration.jsx
your pr does not contain the toggle functionality whiich was added in #386  please update your branch and give a pr

2024-05-26 07:08 UTC, codewarnab commented
> > ## Description
> > [Please include a brief description of the changes or features added] in full screen and mobile screen display different different UI
> > ## Related Issue
> > [Cite any related issue(s) this pull request addresses. If none, simply state "None"] responsive UI of sign up #374 and closed #374
> > ## Screenshots / GIFs (if applicable)
> > [Attach any relevant screenshots or GIFs demonstrating the changes] in full screen: ![image](https://private-user-images.githubusercontent.com/137641079/333849300-ad4921c6-3bdb-4154-ae6f-1b36b7e392b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDcwNTAsIm5iZiI6MTcxNjcwNjc1MCwicGF0aCI6Ii8xMzc2NDEwNzkvMzMzODQ5MzAwLWFkNDkyMWM2LTNiZGItNDE1NC1hZTZmLTFiMzZiN2UzOTJiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQwNjU5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYzg2YjZjMThlZmU4ZTg3MjcxNjRlYjljNDUxNDY0YWFmMGFhMjc1OGI2Mjg5OWYzMmYzZjU4YjI3YjkzZjhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5bxqYYSUuwqqGQySB69VkaT3dz9zgnExEiHmYKY2Hu4) in mobile screen: ![image](https://private-user-images.githubusercontent.com/137641079/333849386-209b5626-8d49-4fe5-bddc-f99720bc0ad8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDcwNTAsIm5iZiI6MTcxNjcwNjc1MCwicGF0aCI6Ii8xMzc2NDEwNzkvMzMzODQ5Mzg2LTIwOWI1NjI2LThkNDktNGZlNS1iZGRjLWY5OTcyMGJjMGFkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQwNjU5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYTAxMjI3ZGI3ZTlhZWRhYzVjNDNhOGM3MWQwOTU2YjFkZGQ4NjZiYzc4YzExMGM1YjRmNTM4YWI4ZTQ0Zjk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M22hhJtjvPZTbEOCLZXpgJwBe2g2XcmLHebEjcVgJvE)
> > ## Checklist:
> > 
> > * [x]   I have performed a self-review of my code
> > * [x]   I have added/updated relevant documentation (if needed)
> > * [x]   I have tested the changes locally and they function as expected
> > * [x]   I have ensured my code follows the project's coding standards
> > 
> > ## Additional Notes
> > [Add any additional notes or context about the changes made]
> 
> ![image](https://private-user-images.githubusercontent.com/94959855/333854370-47034796-89a1-4140-8b4b-1cea0c95695e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDc1ODQsIm5iZiI6MTcxNjcwNzI4NCwicGF0aCI6Ii85NDk1OTg1NS8zMzM4NTQzNzAtNDcwMzQ3OTYtODlhMS00MTQwLThiNGItMWNlYTBjOTU2OTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDA3MDgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1ODE4YTcxNzM1Y2VlNjc4YTM1ZGRmYjE1ZGYxNGE3NzEyNzg0MjUyZTI4ZjEyZGJlZmQyNzk4NDgxNjBlMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GSNHaHrBrMNtIOPG_qleQsweN1uRUK01p4Un8h21H3k) just tested it locally it is not responsive your phone can you share the full screen with dimesions also for mobile

i think it will be better if you just remove the dog image in mobile screeen

2024-05-26 07:51 UTC, Varsani2520 commented
Ok I'll try

2024-05-26 07:51 UTC, Varsani2520 commented on src/pages/user/UserRegistration.jsx
Ok

2024-05-26 13:18 UTC, Varsani2520 reviewed
i remove dog img in mobile device

2024-05-29 04:40 UTC, Varsani2520 commented
Hey @codewarnab ,i solved the conflick now you are ready to merge and if yu want any changed then inform me ,i can do it

2024-05-30 07:02 UTC, codewarnab commented
> Hey @codewarnab ,i solved the conflick now you are ready to merge and if yu want any changed then inform me ,i can do it

its  looks perfect but their was conflict again so try to fix this , or maybe just a create a new fork and put your changes their as their many new code added in that page

2024-05-30 08:41 UTC, Varsani2520 commented
@codewarnab ,i  solve the conflict ,now you can check

2024-05-31 04:02 UTC, Varsani2520 commented
Hey @codewarnab ,
i solved the conflicts 

please merge it and close the issue #374

2024-05-31 09:27 UTC, codewarnab commented
are you facing the same error #440 ? if yes can u please fix this in your pr not a major issue for creating a different pr

2024-05-31 11:54 UTC, Varsani2520 commented
@codewarnab ,
if you merge it then automatically solve the #440

2024-05-31 11:55 UTC, Varsani2520 commented
merge and also come any error then tell me i also solve that , i already know about error is not come

2024-05-31 12:45 UTC, merged