Register and Login page responsive
Innovateninjas/Paws-frontend pull request #462
Opened 2024-06-05 09:22 UTC by the-t3ch-wizard

## Description
Removed some unnecessary code from UserRegistration page.
Made Register and Login page responsive.

Fixes #450 , #419 and #380 

## Related Issue
None

## Screenshots / GIFs (if applicable)
![Screenshot 2024-06-05 144802](https://github.com/Innovateninjas/Paws-frontend/assets/120236359/91a97f08-6769-4831-9c37-dcce9a2d5468)
![Screenshot 2024-06-05 144751](https://github.com/Innovateninjas/Paws-frontend/assets/120236359/e839b175-eb8e-4b9e-97e9-2428c275890b)

## Checklist:
- [x ] I have performed a self-review of my code
- [ ] I have added/updated relevant documentation (if needed)
- [ x] I have tested the changes locally and they function as expected
- [x ] I have ensured my code follows the project's coding standards

## Additional Notes
None

2024-06-05 17:14 UTC, codewarnab commented
> ## Description
> Removed some unnecessary code from UserRegistration page. Made Register and Login page responsive.
> 
> Fixes #450 , #419 and #380
> 
> ## Related Issue
> None
> 
> ## Screenshots / GIFs (if applicable)
> ![Screenshot 2024-06-05 144802](https://private-user-images.githubusercontent.com/120236359/336772977-91a97f08-6769-4831-9c37-dcce9a2d5468.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MDc4ODAsIm5iZiI6MTcxNzYwNzU4MCwicGF0aCI6Ii8xMjAyMzYzNTkvMzM2NzcyOTc3LTkxYTk3ZjA4LTY3NjktNDgzMS05YzM3LWRjY2U5YTJkNTQ2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQxNzEzMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2MzNDEwY2QyODg1Zjc3N2M5OTI5ZGM5NWFhNDU4OTlhZTA4OGJkMWY4NDZhZjJhNGYxNGI4NWQ0YjYyOWM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gzgXSBQ1M0dR1-FvRN4BvzvWkWR756Aqr3OJW7WIqcE) ![Screenshot 2024-06-05 144751](https://private-user-images.githubusercontent.com/120236359/336772995-e839b175-eb8e-4b9e-97e9-2428c275890b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MDc4ODAsIm5iZiI6MTcxNzYwNzU4MCwicGF0aCI6Ii8xMjAyMzYzNTkvMzM2NzcyOTk1LWU4MzliMTc1LWViOGUtNGI5ZS05N2U5LTI0MjhjMjc1ODkwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQxNzEzMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTgzOGQwYWI4NGUzMzVkNDZjOTIzOTljODVkMjhhZDYxYjBmZDU5MDMxNzYyYmY0MzNlNWFhMmFjZWE5MjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7EKew84UZK7WcqP6YwYkys5dXYZ72Do-TV5z5VE4-hY)
> 
> ## Checklist:
> * [x]  I have performed a self-review of my code
> * [x]  I have added/updated relevant documentation (if needed)
> * [x]  I have tested the changes locally and they function as expected
> * [x]  I have ensured my code follows the project's coding standards
> 
> ## Additional Notes
> None

hey you did good job are you contributing under gssoc ?

2024-06-05 17:22 UTC, codewarnab commented
![image](https://github.com/Innovateninjas/Paws-frontend/assets/94959855/459a5395-c13d-4b49-949b-44ae37a9d5db)
make the create account text little bit more smaller 
![image](https://github.com/Innovateninjas/Paws-frontend/assets/94959855/9f04fc41-e6e0-4ad6-9833-004463a77c89)
decrease this padding from all sides probabalu this will fit the create account text in one line which will look better

2024-06-05 17:34 UTC, the-t3ch-wizard commented
I'm working on the conflicts and will inform as soon as possible.

2024-06-05 18:04 UTC, the-t3ch-wizard commented
is the conflicts resolved?

2024-06-05 18:28 UTC, the-t3ch-wizard commented
@codewarnab  Please review my PR.
I have improved the ui as requested.
and since you asked, no i'm not contributing under gssoc

2024-06-06 15:13 UTC, codewarnab requested changes

2024-06-06 15:13 UTC, codewarnab commented on src/pages/user/UserRegistration.jsx
> +    fontSize: "18px",
its still has duplicate keys

2024-06-06 15:14 UTC, codewarnab commented
> ![image](https://private-user-images.githubusercontent.com/94959855/336941238-459a5395-c13d-4b49-949b-44ae37a9d5db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2ODcxMTgsIm5iZiI6MTcxNzY4NjgxOCwicGF0aCI6Ii85NDk1OTg1NS8zMzY5NDEyMzgtNDU5YTUzOTUtYzEzZC00YjQ5LTk0OWItNDRhZTM3YTlkNWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE1MTMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyYjUyNzQ0Y2Q1Yjc5OWUwYWU5ODQzNzdkYzc1MjhkNzcxYTU1NjFjMDI5MzFjNjkwMmQ3NWYwZDEzMWZkMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EWxbs0MZs_ssMo3V3Z3o9PgWZlQ8rT4QGSQDE41kBNs) make the create account text little bit more smaller ![image](https://private-user-images.githubusercontent.com/94959855/336941460-9f04fc41-e6e0-4ad6-9833-004463a77c89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2ODcxMTgsIm5iZiI6MTcxNzY4NjgxOCwicGF0aCI6Ii85NDk1OTg1NS8zMzY5NDE0NjAtOWYwNGZjNDEtZTZlMC00YWQ2LTk4MzMtMDA0NDYzYTc3Yzg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE1MTMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0OTYwZmY5YzZjOGU4NDU5MWY4NjY4NDI0OTQ0NWYwNjAyNTRhYTdhMmUyMWYxM2M3NTUyMmZiZGNiMGRiODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yjkNxQD8lLl-nl5I4IlRQtMQm4MG3l985EfD-QhJEoQ) decrease this padding from all sides probabalu this will fit the create account text in one line which will look better

also did you chanages this what i mentioned ?

2024-06-06 16:25 UTC, the-t3ch-wizard commented on src/pages/user/UserRegistration.jsx
> +    fontSize: "18px",
I had removed the duplicate keys in my recent commit.

2024-06-06 16:28 UTC, the-t3ch-wizard commented
> > ![image](https://private-user-images.githubusercontent.com/94959855/336941238-459a5395-c13d-4b49-949b-44ae37a9d5db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2ODcxMTgsIm5iZiI6MTcxNzY4NjgxOCwicGF0aCI6Ii85NDk1OTg1NS8zMzY5NDEyMzgtNDU5YTUzOTUtYzEzZC00YjQ5LTk0OWItNDRhZTM3YTlkNWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE1MTMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyYjUyNzQ0Y2Q1Yjc5OWUwYWU5ODQzNzdkYzc1MjhkNzcxYTU1NjFjMDI5MzFjNjkwMmQ3NWYwZDEzMWZkMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EWxbs0MZs_ssMo3V3Z3o9PgWZlQ8rT4QGSQDE41kBNs) make the create account text little bit more smaller ![image](https://private-user-images.githubusercontent.com/94959855/336941460-9f04fc41-e6e0-4ad6-9833-004463a77c89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2ODcxMTgsIm5iZiI6MTcxNzY4NjgxOCwicGF0aCI6Ii85NDk1OTg1NS8zMzY5NDE0NjAtOWYwNGZjNDEtZTZlMC00YWQ2LTk4MzMtMDA0NDYzYTc3Yzg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE1MTMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0OTYwZmY5YzZjOGU4NDU5MWY4NjY4NDI0OTQ0NWYwNjAyNTRhYTdhMmUyMWYxM2M3NTUyMmZiZGNiMGRiODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yjkNxQD8lLl-nl5I4IlRQtMQm4MG3l985EfD-QhJEoQ) decrease this padding from all sides probabalu this will fit the create account text in one line which will look better
> 
> also did you chanages this what i mentioned ?

Yes I have improved the ui as per requested
The mobile ui :
![Screenshot 2024-06-06 214828](https://github.com/Innovateninjas/Paws-frontend/assets/120236359/ef48c9a9-c796-42e2-ac0f-c0a0efd81ca4)
The tablet ui : 
![Screenshot 2024-06-06 215750](https://github.com/Innovateninjas/Paws-frontend/assets/120236359/f8b47ad0-9e3e-4828-96a4-40fddc8b1fc1)

2024-06-06 16:44 UTC, the-t3ch-wizard commented on src/pages/user/UserRegistration.jsx
>  import LoginTextLink from "../../Components/shared/LoginTextLink";
I have added this feature too in my latest commit

2024-06-09 03:05 UTC, the-t3ch-wizard commented
@codewarnab is there something more that is required to be done here?

2024-06-09 05:12 UTC, codewarnab commented
> @codewarnab is there something more that is required to be done here?

no its ok i will merge soon after reviewing ,i am little busy with  my exams ...

2024-06-22 10:07 UTC, codewarnab commented
good job

2024-06-22 10:07 UTC, merged