feat: Paws Loader added with responsive
Innovateninjas/Paws-frontend pull request #483
Opened 2024-06-09 06:28 UTC by RamakrushnaBiswal

## Description
Paws Loader added with responsive
## Related Issue
#469 solved

## Screenshots / GIFs (if applicable)

https://github.com/Innovateninjas/Paws-frontend/assets/125277258/c315c0ae-3e39-4641-8861-cc2387ebf74c

![image](https://github.com/Innovateninjas/Paws-frontend/assets/125277258/6b48ca75-a671-4fc1-be59-5042da29a5b8)

## Checklist:
- [ ] I have performed a self-review of my code
- [ ] I have added/updated relevant documentation (if needed)
- [ ] I have tested the changes locally and they function as expected
- [ ] I have ensured my code follows the project's coding standards

## Additional Notes
[Add any additional notes or context about the changes made]

2024-06-09 13:50 UTC, codewarnab requested changes

2024-06-09 13:50 UTC, codewarnab commented on src/App.jsx
you have to cleanup the setTimeout 
```useEffect(() => {
    const timer = setTimeout(() => {
      setLoading(false);
    }, 2500);

    // Cleanup function to clear the timeout
    return () => clearTimeout(timer);
  }, []);
  ```

2024-06-09 13:50 UTC, codewarnab commented on src/Components/shared/loader.jsx
this component is also being used in the  userprofile page and ngo profile page you have chanaged the props so check if they are working properply or not or any modification needed 
try to add loading for those pages also

2024-06-10 04:06 UTC, RamakrushnaBiswal commented on src/App.jsx
done

2024-06-10 04:21 UTC, RamakrushnaBiswal commented on src/Components/shared/loader.jsx
solved

2024-06-10 04:22 UTC, RamakrushnaBiswal commented
@codewarnab review the PR

2024-06-10 13:16 UTC, codewarnab requested changes

2024-06-10 13:16 UTC, codewarnab commented on src/utils/contexts/NgoContext.js
i did not understand why did you returning the component from here ? 
i just told to handle this in profile pages file 
![image](https://github.com/Innovateninjas/Paws-frontend/assets/94959855/9d6ca6ab-eae3-4ac2-9513-42463a2ba002)
its passes a prop which is not in the current loader 
however do not chanage main loader please create seperate loader file which will be shown during first load (app.jsx) load and old loader will be same 
create loader folder their will be two loader file 
also revert this two  context file

2024-06-11 02:21 UTC, RamakrushnaBiswal commented on src/utils/contexts/NgoContext.js
done

2024-06-12 04:42 UTC, RamakrushnaBiswal commented
@codewarnab review the PR

2024-06-17 16:41 UTC, closed without merging

2024-06-18 14:10 UTC, codewarnab commented
#475