R
Innovateninjas/Paws-frontend pull request #508
Opened 2024-06-25 19:18 UTC by taneeshaa15

Hi  ,
I hope you're doing well. I've addressed the issue #505  and created a pull request to resolve it.
Could you please review the PR and let me know if any adjustments are needed?

Best regards,
Tanisha Garg

2024-06-26 03:09 UTC, codewarnab requested changes

2024-06-26 03:09 UTC, codewarnab commented on src/App.css
you just chanaged the app.css fonts path how its #505 ? 
also this is an vite  app public folder is eserved as root path why did you chanaged it ?

2024-06-26 14:10 UTC, taneeshaa15 commented on src/App.css
I just tried to make it optimizable for mobile screens.

2024-06-26 17:55 UTC, taneeshaa15 commented
@codewarnab Tell me the adjustments needed now.

2024-06-27 20:10 UTC, codewarnab commented
add screenshot of team page

2024-06-30 16:37 UTC, taneeshaa15 commented
@codewarnab Will complete it as soon as possible.

2024-07-01 16:59 UTC, taneeshaa15 commented
@codewarnab Please review.

2024-07-02 04:37 UTC, codewarnab commented
> add screenshot of team page

.

2024-07-02 15:18 UTC, taneeshaa15 commented
@codewarnab Here is the screenshot of team page after updation:

![Screenshot from 2024-07-02 20-47-07](https://github.com/Innovateninjas/Paws-frontend/assets/157527085/f1fdb1e6-d1a1-4002-835a-100fe2248558)

2024-07-04 11:14 UTC, merged