added the Happy Recovery Story page
Innovateninjas/Paws-frontend pull request #519
Opened 2024-07-06 09:40 UTC by anagha-chaudhari

## Description
As stated in the issue #495 I have added a page that showcases the rescuers and the recovery stories of the rescued animals

## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None"]

## Screenshots / GIFs (if applicable)
![paws1](https://github.com/Innovateninjas/Paws-frontend/assets/143149376/cd860894-2130-4126-9670-3123807d3a98)

https://github.com/Innovateninjas/Paws-frontend/assets/143149376/e8572fa5-8df8-48a0-972d-34672f301309

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have added/updated relevant documentation (if needed)
- [x] I have tested the changes locally and they function as expected
- [x] I have ensured my code follows the project's coding standards

## Additional Notes
I have made the folder under src / pages / user / RecoveredsPage
The required images are added in the images folder of the RecoveredsPage folder.
Please review the PR, and if there are any changes required, let me know

2024-07-06 19:26 UTC, codewarnab commented
good work but in the issue comments i mentioned that it will be added in landing page which is not ready , so do one thing just create a separate route for this no need to add any tab in the nav bar in the exisiting ui

2024-07-07 10:02 UTC, anagha-chaudhari commented
Hello @codewarnab, I'm sorry for my mistake. I have removed the tab from the navbar, and the path to the page is **/recovereds-page** Please review once again

2024-07-08 09:50 UTC, anagha-chaudhari commented
@codewarnab please review

2024-07-09 14:57 UTC, codewarnab requested changes

2024-07-09 14:57 UTC, codewarnab commented on src/Components/shared/Navbar.jsx
> +              /*<BottomNavigationAction key="RecoveredsPage" value="/recovereds-page" showLabel label="Stories" component={Link} to="/recovereds-page" icon={<FaPaw size={28} />} />, // for recovered
remove this part

2024-07-09 14:57 UTC, codewarnab commented on src/Components/shared/Navbar.jsx
> +import { FaUser, FaUserPlus, FaPaw } from 'react-icons/fa';
remove this icon

2024-07-09 14:57 UTC, codewarnab commented on src/Components/shared/Navbar.jsx
if possible revert this file as before

2024-07-09 15:17 UTC, anagha-chaudhari commented
I have made the changes and added the original initial code to Navbar.jsx, please check @codewarnab

2024-07-11 07:38 UTC, anagha-chaudhari commented
I have done changes and added the current original code of navbar to Navbar.jsx, please check @codewarnab

2024-07-13 20:35 UTC, codewarnab approved these changes

2024-07-13 20:36 UTC, merged